config/routes.rb
Ticketee::Application.routes.draw do

  root to: 'projects#index'

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root to: 'base#index'

    resources :users do
      resources :permissions
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  get '/awaiting_confirmation', to: "users#confirmation", as: 'confirm_user'

  put '/admin/users/:user_id/permissions', to: "admin/permissions#update", as: :update_user_permissions
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :delete_all
  validates :name, presence: true, uniqueness: true
  has_many :permissions, as: :thing

  scope :readable_by,
        lambda { |user| joins(:permissions).where(permissions: { action: "view", user_id: user.id }) }

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authorize_admin!, except: [:index, :show]
  before_filter :authenticate_user!, only: [:index, :show]
  before_filter :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user).all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        flash[:alert] = 'Project has not been created.'
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @tickets = @project.tickets

    respond_to do |format|
      format.html
      format.json { render json: @project }
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been successfully updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render action: :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been successfully deleted."
    redirect_to projects_path
  end

  private

  def find_project
    begin
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project could not be found."
      redirect_to projects_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name, "Project Name" %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h3>Edit Project</h3>

<%= render "form" %>

app/views/projects/index.html.erb
<h3>Projects</h3>

<ul id="projects">
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

<%= admins_only do %>
  <%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h3>New Project</h3>

<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<%= form_tag search_project_tickets_path(@project), method: :get do %>
  <%= label_tag "search" %>
  <%= text_field_tag "search", params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<ul id="tickets">
  <% @tickets.each do |ticket| %>
    <li>
      <%= render ticket.state if ticket.state %>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', projects_path %> |
<%= admins_only do %>
  <%= link_to 'Edit Project', edit_project_path(@project) %> |
  <%= link_to 'Delete Project', @project, method: :delete, confirm: "Are you sure you want to delete this project?" %> |
<% end %>
<%= authorized?("create ticket".to_sym, @project) do %>
  <%= link_to "New Ticket", new_project_ticket_path(@project) %>
<% end %>