config/routes.rb
Ticketee::Application.routes.draw do

  root to: 'projects#index'

  resources :projects do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end

  resources :files

  namespace :admin do
    root to: 'base#index'

    resources :users do
      resources :permissions
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  get '/awaiting_confirmation', to: "users#confirmation", as: 'confirm_user'

  put '/admin/users/:user_id/permissions', to: "admin/permissions#update", as: :update_user_permissions
end

app/models/state.rb
class State < ActiveRecord::Base

  def to_s
    name
  end

  def default!
    current_default = State.find_by_default(true)

    if (current_default)
      current_default.default = false
      current_default.save!
    end

    self.default = true
    self.save!
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController

  def index
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(params[:state])

    if @state.save
      redirect_to admin_states_path, notice: "State has been successfully created."
    else
      render action: :new, alert: "State has not been created."
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.default!

    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
  end
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>

<ul id="states">
  <% @states.each do |state| %>
    <li id='state_<%= state.id %>'>
      <%= state.name %>
      <% if state.default? %>
        (Default)
      <% else %>
        <%= link_to "Make Default", make_default_admin_state_path(state) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h3>New State</h3>

<%= render "form" %>